# Generated by Django 5.0.6 on 2024-07-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_cart_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Discounted_p_Price',
            new_name='Discounted_Price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity',
        ),
    ]
