# Generated by Django 5.0.6 on 2024-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_discounted_p_price_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
