# Generated by Django 5.0.6 on 2024-07-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_otprecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRecord',
        ),
        migrations.AddField(
            model_name='customer',
            name='OTP',
            field=models.CharField(default='', max_length=4),
        ),
    ]
