# Generated by Django 5.0.4 on 2024-07-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_delete_otprecord_customer_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='OTP',
        ),
    ]
